package com.muy257.themecompat.settings;

import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import java.util.zip.ZipEntry;
import java.util.zip.ZipFile;

/**
 * Identifies a theme generated by this patcher from the applied theme's own
 * payload. The patcher writes a versioned marker record into every module
 * archive it rewrites, and the theme engine copies each module archive
 * verbatim into /data/system/theme/&lt;package&gt; on every apply, so finding
 * the marker there proves the currently applied theme came from this patcher.
 *
 * The secure "maml" metadata is deliberately not consulted. HyperOS copies
 * description.xml's description into it when a theme with a maml component is
 * applied, but leaves it untouched when a later theme has no such component,
 * which made every theme applied after an adapted one look adapted too.
 *
 * Missing/unreadable state stays UNKNOWN: callers may install resource-backed
 * surface adapters, but must skip card/overlay mutations which could
 * otherwise damage stock UI.
 */
final class ThemeCompatibilityGate {
    enum Status { COMPATIBLE, INCOMPATIBLE, UNKNOWN }

    private ThemeCompatibilityGate() { }

    static Status inspect() {
        return evaluate(new File("/data/system/theme"));
    }

    static Status evaluate(File themeDir) {
        File[] files = themeDir.listFiles();
        if (files == null) return Status.UNKNOWN;
        Arrays.sort(files);
        boolean sawArchive = false;
        for (File file : files) {
            if (file.isDirectory()) continue;
            try (ZipFile zip = new ZipFile(file)) {
                ZipEntry marker = zip.getEntry(CompatibilityContract.PAYLOAD_MARKER_ENTRY);
                if (marker != null && payloadHasMarker(zip, marker)) {
                    return Status.COMPATIBLE;
                }
                sawArchive = true;
            } catch (IOException | SecurityException ignored) {
                // Unreadable and non-archive entries (images, xml config)
                // prove nothing either way; module archives decide below.
            }
        }
        return sawArchive ? Status.INCOMPATIBLE : Status.UNKNOWN;
    }

    private static boolean payloadHasMarker(ZipFile zip, ZipEntry marker) throws IOException {
        byte[] expected = CompatibilityContract.PAYLOAD_MARKER_CONTENT.getBytes(StandardCharsets.UTF_8);
        byte[] content = new byte[expected.length];
        try (InputStream input = zip.getInputStream(marker)) {
            int read = 0;
            while (read < content.length) {
                int chunk = input.read(content, read, content.length - read);
                if (chunk < 0) return false;
                read += chunk;
            }
        }
        return Arrays.equals(content, expected);
    }
}
