package com.muy257.themecompat.settings;

import android.content.Context;
import android.provider.Settings;

/**
 * Identifies a theme generated by this patcher without trusting an editable
 * author name. HyperOS copies description.xml's description into the secure
 * "maml" JSON when the theme is applied, so the versioned patch marker is the
 * machine-readable proof. Missing/unreadable metadata stays UNKNOWN: callers
 * may install resource-backed surface adapters, but must skip card/overlay
 * mutations which could otherwise damage stock UI.
 */
final class ThemeCompatibilityGate {
    enum Status { COMPATIBLE, INCOMPATIBLE, UNKNOWN }

    private ThemeCompatibilityGate() { }

    static Status inspect(Context context) {
        if (context == null) return Status.UNKNOWN;
        try {
            String maml = Settings.Secure.getString(context.getContentResolver(), "maml");
            if (maml == null || maml.trim().isEmpty() || "null".equals(maml)) {
                return Status.UNKNOWN;
            }
            return maml.contains(CompatibilityContract.PATCH_MARKER)
                    ? Status.COMPATIBLE : Status.INCOMPATIBLE;
        } catch (Throwable ignored) {
            return Status.UNKNOWN;
        }
    }
}
